### ISSUE TITLE
Rebase to the latest version of the base64

### ISSUE THREAD

**Issue by vglavnyy** [BurningEnlightenment/base64-cmake#1]
I did fork from your repo and rebase it to the latest state of aklomp/base64 library.
Also, fix the benchmark under windows.

I'm not sure I did it right.
Rebasing of your commits was the right way?

Can you see my repo before pull request?

https://github.com/vglavnyy/base64-cmake/commits/feature/cmake

**Comment by BurningEnlightenment** [comment]
I'm currently on holidays; I'll review this next week. However, thanks for the effort!

**Comment by BurningEnlightenment** [comment]
I pulled (most of) your changes, thanks!
Additional Notes:
* Usually I do prefer rebasing, but in this specific case I went with a merge of the master branch, because I think that maintaining the commit-tree history for long standing branches is beneficial.
* I excluded your benchmark fixes as they only remotely belong to this feature branch, please file a pr against upstream or participate in aklomp/base64#6
